GET http://127.0.0.1:8081/api/checkout/5

###

POST http://127.0.0.1:8081/api/reservation/5?
 request={"passengers":[{"travelerType":"ADT", "first":"Pushakrev","last":"Pushkarev","prefix":"Mr"}],"address":{"street":"Pobeda striie","postalCode":32,"city":"Grad","country":"RS"},"airSolutionKey":"/ggZhOfYlDKAherHhGAAAA==","email":"psuk@bk.ru","phoneNumber":"381637796918"}

###

