GET http://127.0.0.1:8081/api/guide/autocomplete/iata/b/dep/DME/?apilang=rs

###
GET http://127.0.0.1:8081/api/guide/airlines/all

###
GET http://127.0.0.1:8081/api/flights/search/request/3

###
POST http://127.0.0.1:8081/api/flights/search/request?
 request={"segments":[{"departure":{"IATA":"BEG","isCity":true},"arrival":{"IATA":"TIV","isCity":false},"departureDate":"2020-05-24T00:00:00"}],"passengers":[{"type":"ADT","count":1}],"parameters":{"direct":false,"aroundDates":0,"serviceClass":"Economy","flightNumbers":null,"airlines":[],"delayed":true}}

###