GET http://127.0.0.1:8081/api/guide/autocomplete/iata/belgra/dep/BEG?apilang=rs

###
GET http://127.0.0.1:8081/api/guide/airlines/all

###
GET http://127.0.0.1:8081/api/guide/airports/ADE

###
GET http://127.0.0.1:8081/api/flights/search/request/48

###
POST http://127.0.0.1:8081/api/flights/search/results/16

###
POST https://v2.ekarte.rs/api/flights/search/results/762

###
GET http://127.0.0.1:8081/api/flights/search/results/16

###
POST http://127.0.0.1:8081/api/flights/search/request?
 request={"segments":[{"departure":{"IATA":"BEG","isCity":true},"arrival":{"IATA":"SIN","isCity":true},"departureDate":"2020-11-11T00:00:00"},{"departure":{"IATA":"SIN","isCity":true},"arrival":{"IATA":"BEG","isCity":true},"departureDate":"2020-11-18T00:00:00"}],"passengers":[{"type":"ADT","count":2},{"type":"CLD","count":1},{"type":"INF","count":1}],"parameters":{"direct":false,"aroundDates":0,"serviceClass":"Economy","flightNumbers":null,"airlines":[],"delayed":true}}
###

// Example 1: {"segments":[{"departure":{"IATA":"BEG","isCity":true},"arrival":{"IATA":"TIV","isCity":false},"departureDate":"2020-05-24T00:00:00"}],"passengers":[{"type":"ADT","count":1}],"parameters":{"direct":false,"aroundDates":0,"serviceClass":"Economy","flightNumbers":null,"airlines":[],"delayed":true}}
// Example 2: {"segments":[{"departure":{"IATA":"BEG","isCity":true},"arrival":{"IATA":"TIV","isCity":false},"departureDate":"2020-09-15T00:00:00"},{"departure":{"IATA":"TIV","isCity":false},"arrival":{"IATA":"BEG","isCity":true},"departureDate":"2020-09-25T00:00:00"}],"passengers":[{"type":"ADT","count":3},{"type":"CLD","count":2},{"type":"INF","count":1},{"type":"INS","count":1}],"parameters":{"direct":false,"aroundDates":0,"serviceClass":"Economy","flightNumbers":null,"airlines":[],"delayed":true}}
// Example 3: {"segments":[{"departure":{"IATA":"BEG","isCity":true},"arrival":{"IATA":"TIV","isCity":false},"departureDate":"2020-09-15T00:00:00"},{"departure":{"IATA":"TIV","isCity":false},"arrival":{"IATA":"LJU","isCity":false},"departureDate":"2020-10-22T00:00:00"},{"departure":{"IATA":"LON","isCity":true},"arrival":{"IATA":"FRA","isCity":false},"departureDate":"2021-01-14T00:00:00"}],"passengers":[{"type":"ADT","count":3},{"type":"CLD","count":2},{"type":"INF","count":1},{"type":"INS","count":2}],"parameters":{"direct":false,"aroundDates":0,"serviceClass":"Business","flightNumbers":null,"airlines":["JU"],"delayed":true}}

POST http://127.0.0.1:8081/api/system/logger/error?user_language_get_change=en&
 searchId=2332&
 error[name]=TypeError&
 error[stack][0][line]=96&
 error[stack][2][path]: https://v2.ekarte.rs/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp

###
GET http://127.0.0.1:8081/api/flights/search/history

###
GET http://127.0.0.1:8081/api/flights/search/flightInfo/171

###
POST https://data.reservio.flights/api/flights/search/results/752?user_language_get_change=sr
###